2021-04-01 at 11:59:15 🔖   INFO     Found additional log level customization: 💪   SUCCESS                                                💻 log.py@init:75 ⏰ 0:00:02.079627
2021-04-01 at 11:59:15 🔖   INFO     Found additional log level customization: 👀   WARN                                                   💻 log.py@init:75 ⏰ 0:00:02.081628
2021-04-01 at 11:59:15 🔖   INFO     Found additional log level customization: 🔖   INFO                                                   💻 log.py@init:75 ⏰ 0:00:02.083733
2021-04-01 at 11:59:15 🔖   INFO     Found additional log level customization: ❌   ERROR                                                  💻 log.py@init:75 ⏰ 0:00:02.084624
2021-04-01 at 11:59:15 🔖   INFO     Found additional log level customization: 🎯   NOTICE                                                 💻 log.py@init:75 ⏰ 0:00:02.088667
2021-04-01 at 11:59:15 🔖   INFO     Found additional log level customization: 💩   SPAM                                                   💻 log.py@init:75 ⏰ 0:00:02.089626
2021-04-01 at 11:59:15 🔖   INFO     Found additional log level customization: 📝   VERBOSE                                                💻 log.py@init:75 ⏰ 0:00:02.091629
2021-04-01 at 11:59:15 🔖   INFO     Found additional log level customization: 💥   CRITICAL                                               💻 log.py@init:75 ⏰ 0:00:02.092625
2021-04-01 at 11:59:15 🔖   INFO     Start connection to Elasticsearch (guard3.westeurope.cloudapp.azure.com:9200)                        💻 elasticsearch.py@connection:9 ⏰ 0:00:02.093623
2021-04-01 at 11:59:15 💪   SUCCESS  Connection to Elasticsearch (guard3.westeurope.cloudapp.azure.com:9200) established                  💻 elasticsearch.py@connection:17 ⏰ 0:00:02.095628
2021-04-01 at 11:59:15 🎯   NOTICE   JWT authentication enabled                                                                           💻 __init__.py@api:32 ⏰ 0:00:02.096629
2021-04-01 at 11:59:15 🎯   NOTICE   HTTPS not set                                                                                        💻 __init__.py@api:44 ⏰ 0:00:02.098626
2021-04-01 at 11:59:15 🎯   NOTICE   Elastic APM disabled                                                                                 💻 __init__.py@api:50 ⏰ 0:00:02.099627
2021-04-01 at 11:59:16 🔖   INFO     Start initialization index agent-catalog                                                             💻 __init__.py@__init__:30 ⏰ 0:00:02.394625
2021-04-01 at 11:59:19 💪   SUCCESS  Index agent-catalog initialized                                                                      💻 __init__.py@__init__:32 ⏰ 0:00:05.670344
2021-04-01 at 11:59:19 💪   SUCCESS  /catalog/agent/ endpoint configured                                                                  💻 __init__.py@routes:50 ⏰ 0:00:05.708342
2021-04-01 at 11:59:19 🔖   INFO     Start initialization index agent-catalog                                                             💻 __init__.py@__init__:30 ⏰ 0:00:05.710347
2021-04-01 at 11:59:22 💪   SUCCESS  Index agent-catalog initialized                                                                      💻 __init__.py@__init__:32 ⏰ 0:00:08.554977
2021-04-01 at 11:59:22 💪   SUCCESS  /catalog/agent/{id} endpoint configured                                                              💻 __init__.py@routes:50 ⏰ 0:00:08.584092
2021-04-01 at 11:59:22 🔖   INFO     Start initialization index agent-instance                                                            💻 __init__.py@__init__:30 ⏰ 0:00:08.584971
2021-04-01 at 11:59:24 💪   SUCCESS  Index agent-instance initialized                                                                     💻 __init__.py@__init__:32 ⏰ 0:00:10.553734
2021-04-01 at 11:59:24 💪   SUCCESS  /instance/agent/ endpoint configured                                                                 💻 __init__.py@routes:50 ⏰ 0:00:10.577696
2021-04-01 at 11:59:24 🔖   INFO     Start initialization index agent-instance                                                            💻 __init__.py@__init__:30 ⏰ 0:00:10.579699
2021-04-01 at 11:59:25 💪   SUCCESS  Index agent-instance initialized                                                                     💻 __init__.py@__init__:32 ⏰ 0:00:12.112425
2021-04-01 at 11:59:25 💪   SUCCESS  /instance/agent/{id} endpoint configured                                                             💻 __init__.py@routes:50 ⏰ 0:00:12.144349
2021-04-01 at 11:59:25 🔖   INFO     Start initialization index algorithm-catalog                                                         💻 __init__.py@__init__:30 ⏰ 0:00:12.146348
2021-04-01 at 11:59:27 💪   SUCCESS  Index algorithm-catalog initialized                                                                  💻 __init__.py@__init__:32 ⏰ 0:00:13.799913
2021-04-01 at 11:59:27 💪   SUCCESS  /catalog/algorithm/ endpoint configured                                                              💻 __init__.py@routes:50 ⏰ 0:00:13.822946
2021-04-01 at 11:59:27 🔖   INFO     Start initialization index algorithm-catalog                                                         💻 __init__.py@__init__:30 ⏰ 0:00:13.824913
2021-04-01 at 11:59:30 💪   SUCCESS  Index algorithm-catalog initialized                                                                  💻 __init__.py@__init__:32 ⏰ 0:00:16.366276
2021-04-01 at 11:59:30 💪   SUCCESS  /catalog/algorithm/{id} endpoint configured                                                          💻 __init__.py@routes:50 ⏰ 0:00:16.409277
2021-04-01 at 11:59:30 🔖   INFO     Start initialization index algorithm-instance                                                        💻 __init__.py@__init__:30 ⏰ 0:00:16.410275
2021-04-01 at 11:59:31 💪   SUCCESS  Index algorithm-instance initialized                                                                 💻 __init__.py@__init__:32 ⏰ 0:00:18.119014
2021-04-01 at 11:59:31 💪   SUCCESS  /instance/algorithm/ endpoint configured                                                             💻 __init__.py@routes:50 ⏰ 0:00:18.148032
2021-04-01 at 11:59:31 🔖   INFO     Start initialization index algorithm-instance                                                        💻 __init__.py@__init__:30 ⏰ 0:00:18.149013
2021-04-01 at 11:59:33 💪   SUCCESS  Index algorithm-instance initialized                                                                 💻 __init__.py@__init__:32 ⏰ 0:00:20.080599
2021-04-01 at 11:59:33 💪   SUCCESS  /instance/algorithm/{id} endpoint configured                                                         💻 __init__.py@routes:50 ⏰ 0:00:20.104595
2021-04-01 at 11:59:33 🔖   INFO     Start initialization index connection                                                                💻 __init__.py@__init__:30 ⏰ 0:00:20.105595
2021-04-01 at 11:59:36 💪   SUCCESS  Index connection initialized                                                                         💻 __init__.py@__init__:32 ⏰ 0:00:23.025307
2021-04-01 at 11:59:36 💪   SUCCESS  /connection/ endpoint configured                                                                     💻 __init__.py@routes:50 ⏰ 0:00:23.053242
2021-04-01 at 11:59:36 🔖   INFO     Start initialization index connection                                                                💻 __init__.py@__init__:30 ⏰ 0:00:23.054241
2021-04-01 at 11:59:37 💪   SUCCESS  Index connection initialized                                                                         💻 __init__.py@__init__:32 ⏰ 0:00:24.123731
2021-04-01 at 11:59:37 💪   SUCCESS  /connection/{id} endpoint configured                                                                 💻 __init__.py@routes:50 ⏰ 0:00:24.167740
2021-04-01 at 11:59:37 💪   SUCCESS  /dashboard endpoint configured                                                                       💻 __init__.py@routes:50 ⏰ 0:00:24.169731
2021-04-01 at 11:59:37 💪   SUCCESS  /dashboard/{part}/{resource} endpoint configured                                                     💻 __init__.py@routes:50 ⏰ 0:00:24.172731
2021-04-01 at 11:59:37 🔖   INFO     Start initialization index data                                                                      💻 __init__.py@__init__:30 ⏰ 0:00:24.173731
2021-04-01 at 11:59:39 💪   SUCCESS  Index data initialized                                                                               💻 __init__.py@__init__:32 ⏰ 0:00:26.085263
2021-04-01 at 11:59:39 💪   SUCCESS  /data/ endpoint configured                                                                           💻 __init__.py@routes:50 ⏰ 0:00:26.116248
2021-04-01 at 11:59:39 🔖   INFO     Start initialization index data                                                                      💻 __init__.py@__init__:30 ⏰ 0:00:26.117225
2021-04-01 at 11:59:42 💪   SUCCESS  Index data initialized                                                                               💻 __init__.py@__init__:32 ⏰ 0:00:28.263954
2021-04-01 at 11:59:42 💪   SUCCESS  /data/{id} endpoint configured                                                                       💻 __init__.py@routes:50 ⏰ 0:00:28.307969
2021-04-01 at 11:59:42 🔖   INFO     Start initialization index ebpf-program-catalog                                                      💻 __init__.py@__init__:30 ⏰ 0:00:28.308944
2021-04-01 at 11:59:44 💪   SUCCESS  Index ebpf-program-catalog initialized                                                               💻 __init__.py@__init__:32 ⏰ 0:00:30.810860
2021-04-01 at 11:59:44 💪   SUCCESS  /catalog/ebpf-program/ endpoint configured                                                           💻 __init__.py@routes:50 ⏰ 0:00:30.846875
2021-04-01 at 11:59:44 🔖   INFO     Start initialization index ebpf-program-catalog                                                      💻 __init__.py@__init__:30 ⏰ 0:00:30.847836
2021-04-01 at 11:59:45 💪   SUCCESS  Index ebpf-program-catalog initialized                                                               💻 __init__.py@__init__:32 ⏰ 0:00:32.123168
2021-04-01 at 11:59:45 💪   SUCCESS  /catalog/ebpf-program/{id} endpoint configured                                                       💻 __init__.py@routes:50 ⏰ 0:00:32.150165
2021-04-01 at 11:59:45 🔖   INFO     Start initialization index ebpf-program-instance                                                     💻 __init__.py@__init__:30 ⏰ 0:00:32.151164
2021-04-01 at 11:59:47 💪   SUCCESS  Index ebpf-program-instance initialized                                                              💻 __init__.py@__init__:32 ⏰ 0:00:33.288056
2021-04-01 at 11:59:47 💪   SUCCESS  /instance/ebpf-program/ endpoint configured                                                          💻 __init__.py@routes:50 ⏰ 0:00:33.310089
2021-04-01 at 11:59:47 🔖   INFO     Start initialization index ebpf-program-instance                                                     💻 __init__.py@__init__:30 ⏰ 0:00:33.310660
2021-04-01 at 11:59:48 💪   SUCCESS  Index ebpf-program-instance initialized                                                              💻 __init__.py@__init__:32 ⏰ 0:00:35.062195
2021-04-01 at 11:59:48 💪   SUCCESS  /instance/ebpf-program/{id} endpoint configured                                                      💻 __init__.py@routes:50 ⏰ 0:00:35.084195
2021-04-01 at 11:59:48 🔖   INFO     Start initialization index event                                                                     💻 __init__.py@__init__:30 ⏰ 0:00:35.086195
2021-04-01 at 11:59:50 💪   SUCCESS  Index event initialized                                                                              💻 __init__.py@__init__:32 ⏰ 0:00:36.869868
2021-04-01 at 11:59:50 💪   SUCCESS  /event/ endpoint configured                                                                          💻 __init__.py@routes:50 ⏰ 0:00:36.938871
2021-04-01 at 11:59:50 🔖   INFO     Start initialization index event                                                                     💻 __init__.py@__init__:30 ⏰ 0:00:36.940872
2021-04-01 at 11:59:52 💪   SUCCESS  Index event initialized                                                                              💻 __init__.py@__init__:32 ⏰ 0:00:38.429623
2021-04-01 at 11:59:52 💪   SUCCESS  /event/{id} endpoint configured                                                                      💻 __init__.py@routes:50 ⏰ 0:00:38.451636
2021-04-01 at 11:59:52 🔖   INFO     Start initialization index exec-env                                                                  💻 __init__.py@__init__:30 ⏰ 0:00:38.453633
2021-04-01 at 11:59:54 💪   SUCCESS  Index exec-env initialized                                                                           💻 __init__.py@__init__:32 ⏰ 0:00:40.226846
2021-04-01 at 11:59:54 💪   SUCCESS  /exec-env/ endpoint configured                                                                       💻 __init__.py@routes:50 ⏰ 0:00:40.260813
2021-04-01 at 11:59:54 🔖   INFO     Start initialization index exec-env                                                                  💻 __init__.py@__init__:30 ⏰ 0:00:40.262860
2021-04-01 at 11:59:56 💪   SUCCESS  Index exec-env initialized                                                                           💻 __init__.py@__init__:32 ⏰ 0:00:42.548599
2021-04-01 at 11:59:56 💪   SUCCESS  /exec-env/{id} endpoint configured                                                                   💻 __init__.py@routes:50 ⏰ 0:00:42.572742
2021-04-01 at 11:59:56 🔖   INFO     Start initialization index exec-env-type                                                             💻 __init__.py@__init__:30 ⏰ 0:00:42.573302
2021-04-01 at 11:59:57 💪   SUCCESS  Index exec-env-type initialized                                                                      💻 __init__.py@__init__:32 ⏰ 0:00:44.072877
2021-04-01 at 11:59:57 💪   SUCCESS  /type/exec-env/ endpoint configured                                                                  💻 __init__.py@routes:50 ⏰ 0:00:44.095425
2021-04-01 at 11:59:57 🔖   INFO     Start initialization index exec-env-type                                                             💻 __init__.py@__init__:30 ⏰ 0:00:44.097376
2021-04-01 at 12:00:01 💪   SUCCESS  Index exec-env-type initialized                                                                      💻 __init__.py@__init__:32 ⏰ 0:00:47.691340
2021-04-01 at 12:00:01 💪   SUCCESS  /exec-env-type/{id} endpoint configured                                                              💻 __init__.py@routes:50 ⏰ 0:00:47.719342
2021-04-01 at 12:00:01 🔖   INFO     Start initialization index network-link                                                              💻 __init__.py@__init__:30 ⏰ 0:00:47.720341
2021-04-01 at 12:00:03 💪   SUCCESS  Index network-link initialized                                                                       💻 __init__.py@__init__:32 ⏰ 0:00:49.499149
2021-04-01 at 12:00:03 💪   SUCCESS  /network-link/ endpoint configured                                                                   💻 __init__.py@routes:50 ⏰ 0:00:49.546150
2021-04-01 at 12:00:03 🔖   INFO     Start initialization index network-link                                                              💻 __init__.py@__init__:30 ⏰ 0:00:49.547151
2021-04-01 at 12:00:05 💪   SUCCESS  Index network-link initialized                                                                       💻 __init__.py@__init__:32 ⏰ 0:00:51.629357
2021-04-01 at 12:00:05 💪   SUCCESS  /network-link/{id} endpoint configured                                                               💻 __init__.py@routes:50 ⏰ 0:00:51.708357
2021-04-01 at 12:00:05 🔖   INFO     Start initialization index network-link-type                                                         💻 __init__.py@__init__:30 ⏰ 0:00:51.710359
2021-04-01 at 12:00:06 💪   SUCCESS  Index network-link-type initialized                                                                  💻 __init__.py@__init__:32 ⏰ 0:00:53.016433
2021-04-01 at 12:00:06 💪   SUCCESS  /type/network-link/ endpoint configured                                                              💻 __init__.py@routes:50 ⏰ 0:00:53.078436
2021-04-01 at 12:00:06 🔖   INFO     Start initialization index network-link-type                                                         💻 __init__.py@__init__:30 ⏰ 0:00:53.079435
2021-04-01 at 12:00:07 💪   SUCCESS  Index network-link-type initialized                                                                  💻 __init__.py@__init__:32 ⏰ 0:00:53.752693
2021-04-01 at 12:00:07 💪   SUCCESS  /type/network-link/{id} endpoint configured                                                          💻 __init__.py@routes:50 ⏰ 0:00:53.802695
2021-04-01 at 12:00:07 🔖   INFO     Start initialization index pipeline                                                                  💻 __init__.py@__init__:30 ⏰ 0:00:53.803694
2021-04-01 at 12:00:07 💪   SUCCESS  Index pipeline initialized                                                                           💻 __init__.py@__init__:32 ⏰ 0:00:53.996693
2021-04-01 at 12:00:07 💪   SUCCESS  /pipeline/ endpoint configured                                                                       💻 __init__.py@routes:50 ⏰ 0:00:54.028695
2021-04-01 at 12:00:07 🔖   INFO     Start initialization index pipeline                                                                  💻 __init__.py@__init__:30 ⏰ 0:00:54.029701
2021-04-01 at 12:00:08 💪   SUCCESS  Index pipeline initialized                                                                           💻 __init__.py@__init__:32 ⏰ 0:00:54.217705
2021-04-01 at 12:00:08 💪   SUCCESS  /pipeline/{id} endpoint configured                                                                   💻 __init__.py@routes:50 ⏰ 0:00:54.267707
2021-04-01 at 12:00:09 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:00:55.383529
2021-04-01 at 12:00:11 💪   SUCCESS  Connection established with exec-env user-vm (LCP at localhost:4567)                                 💻 heartbeat.py@heartbeat_exec_env:45 ⏰ 0:00:57.434592
2021-04-01 at 12:00:13 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:00:59.430175
2021-04-01 at 12:00:13 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:00:59.445324
2021-04-01 at 12:00:19 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:01:05.410508
2021-04-01 at 12:00:19 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:01:05.411296
2021-04-01 at 12:00:19 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:01:05.411296
2021-04-01 at 12:00:19 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:01:05.411296
2021-04-01 at 12:00:19 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:01:05.536811
2021-04-01 at 12:00:19 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:01:05.536811
2021-04-01 at 12:00:19 💪   SUCCESS  Accept requests at 0.0.0.0:5000                                                                      💻 main.py@<module>:37 ⏰ 0:01:05.538781
2021-04-01 at 12:01:19 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:02:05.781465
2021-04-01 at 12:01:21 💪   SUCCESS  Connection established with exec-env user-vm (LCP at localhost:4567)                                 💻 heartbeat.py@heartbeat_exec_env:45 ⏰ 0:02:07.824180
2021-04-01 at 12:01:23 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:02:09.826670
2021-04-01 at 12:01:23 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:02:09.857682
2021-04-01 at 12:01:29 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:02:15.790960
2021-04-01 at 12:01:29 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:02:15.790960
2021-04-01 at 12:01:29 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:02:15.790960
2021-04-01 at 12:01:29 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:02:15.791962
2021-04-01 at 12:01:29 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:02:15.791962
2021-04-01 at 12:01:29 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:02:15.791962
2021-04-01 at 12:02:29 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:03:16.013141
2021-04-01 at 12:02:33 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:03:20.056012
2021-04-01 at 12:02:33 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:03:20.069643
2021-04-01 at 12:02:33 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:03:20.070645
2021-04-01 at 12:02:39 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:03:26.015845
2021-04-01 at 12:02:39 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:03:26.015845
2021-04-01 at 12:02:39 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:03:26.015845
2021-04-01 at 12:02:39 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:03:26.016843
2021-04-01 at 12:02:39 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:03:26.093628
2021-04-01 at 12:02:39 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:03:26.093628
2021-04-01 at 12:03:40 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:04:26.318385
2021-04-01 at 12:03:42 💪   SUCCESS  Connection established with exec-env user-vm (LCP at localhost:4567)                                 💻 heartbeat.py@heartbeat_exec_env:45 ⏰ 0:04:28.388230
2021-04-01 at 12:03:44 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:04:30.390768
2021-04-01 at 12:03:44 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:04:30.406434
2021-04-01 at 12:03:50 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:04:36.327932
2021-04-01 at 12:03:50 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:04:36.327932
2021-04-01 at 12:03:50 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:04:36.327932
2021-04-01 at 12:03:50 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:04:36.328933
2021-04-01 at 12:03:50 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:04:36.343122
2021-04-01 at 12:03:50 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:04:36.343934
2021-04-01 at 12:04:51 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:05:37.434454
2021-04-01 at 12:04:55 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:05:41.466096
2021-04-01 at 12:04:55 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:05:41.481096
2021-04-01 at 12:04:55 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:05:41.481096
2021-04-01 at 12:05:01 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:05:47.446018
2021-04-01 at 12:05:01 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:05:47.446018
2021-04-01 at 12:05:01 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:05:47.446953
2021-04-01 at 12:05:01 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:05:47.446953
2021-04-01 at 12:05:01 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:05:47.460987
2021-04-01 at 12:05:01 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:05:47.461965
2021-04-01 at 12:06:01 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:06:47.689198
2021-04-01 at 12:06:05 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:06:51.726410
2021-04-01 at 12:06:05 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:06:51.734408
2021-04-01 at 12:06:05 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:06:51.742407
2021-04-01 at 12:06:11 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:06:57.695229
2021-04-01 at 12:06:11 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:06:57.696539
2021-04-01 at 12:06:11 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:06:57.698273
2021-04-01 at 12:06:11 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:06:57.710165
2021-04-01 at 12:06:11 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:06:57.710833
2021-04-01 at 12:06:11 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:06:57.711392
2021-04-01 at 12:07:12 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:07:58.376020
2021-04-01 at 12:07:16 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:08:02.432183
2021-04-01 at 12:07:16 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:08:02.463161
2021-04-01 at 12:07:16 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:08:02.463161
2021-04-01 at 12:07:22 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:08:08.376449
2021-04-01 at 12:07:22 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:08:08.377446
2021-04-01 at 12:07:22 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:08:08.392444
2021-04-01 at 12:07:22 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:08:08.393446
2021-04-01 at 12:07:22 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:08:08.645978
2021-04-01 at 12:07:22 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:08:08.645978
2021-04-01 at 12:08:22 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:09:09.197537
2021-04-01 at 12:08:27 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:09:13.254126
2021-04-01 at 12:08:27 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:09:13.255129
2021-04-01 at 12:08:27 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:09:13.255129
2021-04-01 at 12:08:32 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:09:19.201176
2021-04-01 at 12:08:32 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:09:19.201176
2021-04-01 at 12:08:32 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:09:19.202180
2021-04-01 at 12:08:32 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:09:19.202180
2021-04-01 at 12:08:33 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:09:19.216178
2021-04-01 at 12:08:33 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:09:19.216178
2021-04-01 at 12:09:34 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:10:20.684902
2021-04-01 at 12:09:38 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:10:24.737533
2021-04-01 at 12:09:38 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:10:24.753543
2021-04-01 at 12:09:38 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:10:24.769496
2021-04-01 at 12:09:44 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:10:30.691710
2021-04-01 at 12:09:44 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:10:30.692418
2021-04-01 at 12:09:44 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:10:30.692418
2021-04-01 at 12:09:44 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:10:30.693410
2021-04-01 at 12:09:44 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:10:30.706847
2021-04-01 at 12:09:44 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:10:30.708542
2021-04-01 at 12:10:44 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:11:31.058572
2021-04-01 at 12:10:48 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:11:35.085989
2021-04-01 at 12:10:48 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:11:35.131997
2021-04-01 at 12:10:48 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:11:35.146729
2021-04-01 at 12:10:54 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:11:41.062346
2021-04-01 at 12:10:54 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:11:41.062346
2021-04-01 at 12:10:54 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:11:41.078677
2021-04-01 at 12:10:54 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:11:41.079142
2021-04-01 at 12:10:54 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:11:41.093904
2021-04-01 at 12:10:54 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:11:41.093904
2021-04-01 at 12:11:55 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:12:41.768559
2021-04-01 at 12:11:59 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:12:45.811586
2021-04-01 at 12:11:59 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:12:45.827633
2021-04-01 at 12:11:59 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:12:45.827633
2021-04-01 at 12:12:05 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:12:51.768623
2021-04-01 at 12:12:05 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:12:51.768623
2021-04-01 at 12:12:05 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:12:51.768623
2021-04-01 at 12:12:05 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:12:51.784623
2021-04-01 at 12:12:05 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:12:51.784623
2021-04-01 at 12:12:05 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:12:51.785683
2021-04-01 at 12:13:06 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:13:52.514839
2021-04-01 at 12:13:10 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:13:56.577019
2021-04-01 at 12:13:10 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:13:56.593070
2021-04-01 at 12:13:10 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:13:56.593070
2021-04-01 at 12:13:16 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:14:02.526583
2021-04-01 at 12:13:16 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:14:02.526583
2021-04-01 at 12:13:16 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:14:02.527592
2021-04-01 at 12:13:16 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:14:02.527592
2021-04-01 at 12:13:16 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:14:02.794174
2021-04-01 at 12:13:16 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:14:02.794174
2021-04-01 at 12:14:16 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:15:03.025894
2021-04-01 at 12:14:20 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:15:07.094134
2021-04-01 at 12:14:20 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:15:07.095130
2021-04-01 at 12:14:20 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:15:07.096133
2021-04-01 at 12:14:26 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:15:13.034186
2021-04-01 at 12:14:26 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:15:13.034186
2021-04-01 at 12:14:26 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:15:13.035156
2021-04-01 at 12:14:26 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:15:13.035156
2021-04-01 at 12:14:26 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:15:13.050153
2021-04-01 at 12:14:26 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:15:13.051153
2021-04-01 at 12:15:28 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:16:14.542626
2021-04-01 at 12:15:32 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:16:18.570611
2021-04-01 at 12:15:32 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:16:18.586294
2021-04-01 at 12:15:32 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:16:18.587286
2021-04-01 at 12:15:38 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:16:24.548405
2021-04-01 at 12:15:38 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:16:24.549400
2021-04-01 at 12:15:38 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:16:24.550398
2021-04-01 at 12:15:38 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:16:24.551398
2021-04-01 at 12:15:38 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:16:24.563393
2021-04-01 at 12:15:38 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:16:24.563393
2021-04-01 at 12:16:38 🎯   NOTICE   Exec-env simulation-model-tool (LCP at 192.168.0.172:4000) not enabled                               💻 heartbeat.py@heartbeat_exec_env:54 ⏰ 0:17:24.799621
2021-04-01 at 12:16:42 ❌   ERROR    Connection refused with exec-env network-manager (LCP at localhost:4000)                             💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:17:28.850510
2021-04-01 at 12:16:42 ❌   ERROR    Connection refused with exec-env mobile-phone (LCP at localhost:4321)                                💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:17:28.850510
2021-04-01 at 12:16:42 ❌   ERROR    Connection refused with exec-env user-vm (LCP at localhost:4567)                                     💻 heartbeat.py@heartbeat_exec_env:58 ⏰ 0:17:28.866466
2021-04-01 at 12:16:48 ❌   ERROR    Connection timeout with exec-env frontend (LCP at 139.91.70.90:33664)                                💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:17:34.800551
2021-04-01 at 12:16:48 ❌   ERROR    Connection timeout with exec-env backend-backup (LCP at 20.52.36.121:4000)                           💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:17:34.801550
2021-04-01 at 12:16:48 ❌   ERROR    Connection timeout with exec-env lora (LCP at 11.23.45.33:4000)                                      💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:17:34.801550
2021-04-01 at 12:16:48 ❌   ERROR    Connection timeout with exec-env backend-test (LCP at 35.193.65.139:4444)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:17:34.801550
2021-04-01 at 12:16:48 ❌   ERROR    Connection timeout with exec-env backend-prod (LCP at 35.193.65.139:4000)                            💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:17:34.815557
2021-04-01 at 12:16:48 ❌   ERROR    Connection timeout with exec-env web-server (LCP at guard-lcp01.8bellsresearch.com:4000)             💻 heartbeat.py@heartbeat_exec_env:56 ⏰ 0:17:34.815557
